#!/usr/bin/env python3
"""mp-skills-adoption instrument: three probes over the upstream pack.

One row per JSON object on stdout. Every row carries `probe`, `source` and
`scope`. `scope` is `real` when the input is this repository's own shipped
system and `fixture` when the input is the upstream clone at a pinned commit -
the numbers are about different things and a reader must be able to tell.

  router-yield  run tezgah's own trigger-line extractor over both corpora
  context-cost  the always-on byte cost of each corpus, by the installer's own
                formula (bin/tezgah-setup:1754-1755)
  conflicts     three executable conflict probes: the floating-tag predicate the
                suite implements, the attribution gate's verdict on the pack's
                mandated disclaimer, and the real suite run against a grafted
                candidate skill in a scratch clone

Nothing here mutates the repository: the suite probe runs in a `git clone
--local` under /tmp.
"""
import argparse
import importlib.machinery
import importlib.util
import json
import os
import re
import subprocess
import sys
import tempfile

# The float and the disclaimer are assembled at runtime, the same reason
# tests/test_gate.py assembles its skip marker: a literal here is a literal any
# future corpus widening would pick up.
FLOAT_TAG = "npx skills@" + "latest add mattpocock/skills"
DISCLAIMER = "> *This was generated by AI during " + "triage.*"
# tests/test_skills.py:92, verbatim
FLOAT_RE = re.compile(r"[\w@./-]+@latest\b")


def load(name, path):
    loader = importlib.machinery.SourceFileLoader(name, path)
    spec = importlib.util.spec_from_loader(name, loader)
    mod = importlib.util.module_from_spec(spec)
    loader.exec_module(mod)
    return mod


def rows(*objs):
    for obj in objs:
        print(json.dumps(obj, ensure_ascii=False))


def skill_files(root):
    out = []
    for dirpath, _dirnames, filenames in os.walk(root):
        if "SKILL.md" in filenames:
            out.append(os.path.join(dirpath, "SKILL.md"))
    return sorted(out)


def classify(line):
    if not line:
        return "empty"
    return "trigger" if re.match(r"(?:Also )?[Uu]se\b", line) else "fallback"


def probe_router_yield(args):
    setup = load("tezgah_setup_probe", args.setup)
    # Amendment, recorded in log.md: the protocol's control is the 14 SHIPPED
    # names (bin/tezgah-setup:76-78); walking skills/ also reads the 98 vendored
    # ai-research entries and pm-frameworks, which are a different corpus. Both
    # are reported, as `tezgah-shipped` and `tezgah-tree`, and neither stands in
    # for the other.
    shipped = [os.path.join(args.tezgah, name, "SKILL.md")
               for name in setup.SKILLS]
    for corpus, paths, root, scope in (
            ("tezgah-shipped", shipped, args.tezgah, "real"),
            ("tezgah-tree", skill_files(args.tezgah), args.tezgah, "real"),
            ("upstream", skill_files(args.upstream), args.upstream, "fixture")):
        counts = {"trigger": 0, "fallback": 0, "empty": 0}
        for path in paths:
            line = setup.skill_description(path)
            kind = classify(line)
            counts[kind] += 1
            # The invocation the file declares, read from the same bytes: the
            # split the analysis draws is only checkable if a row carries it.
            with open(path, encoding="utf-8", errors="replace") as fh:
                head = fh.read(6000)
            invoked = ("user" if "disable-model-invocation: true" in head
                       else "model")
            rows({"probe": "router-yield", "corpus": corpus, "name":
                  os.path.basename(os.path.dirname(path)), "class": kind,
                  "invoked": invoked, "chars": len(line), "line": line,
                  "source": path, "scope": scope})
        rows({"probe": "router-yield", "corpus": corpus, "summary": counts,
              "total": sum(counts.values()), "source": root, "scope": scope})


def probe_context_cost(args):
    setup = load("tezgah_setup_probe", args.setup)
    policy = load("tezgah_policy_probe", args.policy)

    def metadata(root, names=None):
        total = 0
        for path in skill_files(root):
            name = os.path.basename(os.path.dirname(path))
            if names is not None and name not in names:
                continue
            total += len(name) + len(setup._frontmatter_description(path)) + 8
        return total

    upstream = skill_files(args.upstream)
    model_invoked = [p for p in upstream
                     if "disable-model-invocation: true" not in
                     open(p, encoding="utf-8").read()]
    rows({
        "probe": "context-cost", "source": "bin/tezgah-setup SKILLS", "scope": "real",
        "tezgah_skills": len(setup.SKILLS),
        "tezgah_metadata_bytes": metadata(args.tezgah, set(setup.SKILLS)),
        "core_bytes": len(policy.CORE), "contract_bytes": len(policy.CONTRACT),
    })
    rows({
        "probe": "context-cost", "source": args.upstream, "scope": "fixture",
        "upstream_skills": len(upstream),
        "upstream_metadata_bytes": metadata(args.upstream),
        "model_invoked_skills": len(model_invoked),
        "model_invoked_metadata_bytes": sum(
            len(os.path.basename(os.path.dirname(p)))
            + len(setup._frontmatter_description(p)) + 8 for p in model_invoked),
    })


def probe_conflicts(args):
    # (a) the predicate the suite implements, over the corpus the suite reads
    corpora = {
        "upstream skills/**/SKILL.md (the suite's corpus)": skill_files(args.upstream),
        "upstream skills/**/*.md": [os.path.join(d, f)
                               for d, _s, fs in os.walk(args.upstream)
                               for f in fs if f.endswith(".md")],
        "tezgah skills (control)": skill_files(args.tezgah),
    }
    for label, paths in corpora.items():
        hits = []
        for path in paths:
            for m in FLOAT_RE.findall(open(path, encoding="utf-8",
                                           errors="replace").read()):
                hits.append({"path": path, "hit": m})
        rows({"probe": "conflicts", "check": "floating-tag", "corpus": label,
              "files": len(paths), "hits": len(hits), "detail": hits[:10],
              "source": "tests/test_skills.py:92", "scope": "fixture"})

    # (b) the attribution gate's verdict on the pack's mandated line
    # Amendment 2 (log.md): tezgah_gate imports its siblings by module name, so
    # the hooks directory has to be importable before it is loaded.
    sys.path.insert(0, os.path.dirname(os.path.abspath(args.gate)))
    gate = load("tezgah_gate_probe", args.gate)
    verdicts = []
    for cmd in ('gh issue comment 42 --body "%s"' % DISCLAIMER,
                'gh issue create --title "x" --body "%s"' % DISCLAIMER,
                'git commit -m "x\n\nCo-Authored-By: Claude"'):
        verdicts.append({"command": cmd, "denied": bool(gate.attribution(cmd))})
    rows({"probe": "conflicts", "check": "attribution-gate", "verdicts": verdicts,
          "source": "hooks/tezgah_gate.py:426 (attribution)", "scope": "real"})

    # (c) the real suite, against a grafted candidate, in a scratch clone
    if args.clone:
        run_suite(args, "with-tag" if args.graft == "tag" else "plain")


def run_suite(args, label):
    dest = tempfile.mkdtemp(prefix="mp-skills-suite-")
    subprocess.run(["git", "clone", "--local", "--quiet", args.repo, dest],
                   check=True)
    base = subprocess.run([sys.executable, "-m", "unittest", "discover",
                           "-s", "tests", "-p", "test_skills.py"],
                          cwd=dest, capture_output=True, text=True)
    body = "test skill body\n"
    if label == "with-tag":
        body = "```bash\n%s\n```\n\n%s" % (FLOAT_TAG, body)
    graft = os.path.join(dest, "skills", "grafted-candidate")
    os.makedirs(graft)
    with open(os.path.join(graft, "SKILL.md"), "w", encoding="utf-8") as fh:
        fh.write("---\nname: grafted-candidate\ndescription: Use when "
                 "the probe grafts a synthetic candidate body.\n---\n\n" + body)
    after = subprocess.run([sys.executable, "-m", "unittest", "discover",
                            "-s", "tests", "-p", "test_skills.py"],
                           cwd=dest, capture_output=True, text=True)
    failed = sorted(set(re.findall(r"^(?:FAIL|ERROR): (\S+)",
                                   after.stderr + after.stdout, re.M)))
    rows({"probe": "conflicts", "check": "suite", "variant": label,
          "baseline_ok": base.returncode == 0, "after_ok": after.returncode == 0,
          "failed": failed, "clone": dest,
          "source": "python3 -m unittest discover -s tests -p test_skills.py",
          "scope": "fixture"})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("probe", choices=["router-yield", "context-cost", "conflicts"])
    ap.add_argument("--repo", default=".")
    ap.add_argument("--upstream", required=True)
    ap.add_argument("--tezgah", default="skills")
    ap.add_argument("--setup", default="bin/tezgah-setup")
    ap.add_argument("--policy", default="hooks/tezgah_policy.py")
    ap.add_argument("--gate", default="hooks/tezgah_gate.py")
    ap.add_argument("--clone", action="store_true")
    ap.add_argument("--graft", default="tag")
    args = ap.parse_args()
    {"router-yield": probe_router_yield, "context-cost": probe_context_cost,
     "conflicts": probe_conflicts}[args.probe](args)


if __name__ == "__main__":
    main()
